apiVersion: v1
kind: Service
metadata:
  name: probes-demo
  namespace: probes-demo
spec:
  selector:
    app: probes-demo
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
